config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :invitations, only: [:index, :new, :create] do
    member do
      post :resend
    end
  end

  resources :refferals, controller: :registrations, only: [:new, :create]

  devise_for :users
  root to: 'club#catty'
end

app/models/invitation.rb
# frozen_string_literal: true
class Invitation < ActiveRecord::Base
  belongs_to :issuer, class_name: 'User', foreign_key: :issuer_id

  validates :token, uniqueness: true, presence: true
  validates :email, presence: true

  def state
    if User.exists?(email: email)
      'registered'
    else
      'pending'
    end
  end

  def registered?
    state == 'registered'
  end
end

app/models/invitation_delivery.rb
# frozen_string_literal: true
class InvitationDelivery
  THROTTLE_DAYS = (ENV['INVITATION_DELIVERY_THROTTLE_DAYS'] || 1).to_i.freeze

  def initialize(invitation)
    @invitation = invitation
  end

  def deliver!
    return [false, ['User is already registered']] if already_registered?
    return [false, ["Can't send invitation until #{I18n.localize next_allowed_time}"]] if been_sent_recently?
    @invitation.update_attributes sent_at: Time.zone.now
    InvitationMailer.notify_user(@invitation).deliver_later

    [true, []]
  end

  private

  def next_allowed_time
    return Time.zone.now if @invitation.sent_at.blank?

    @invitation.sent_at + THROTTLE_DAYS.days
  end

  def been_sent_recently?
    return false if @invitation.sent_at.blank?
    @invitation.sent_at > THROTTLE_DAYS.days.ago
  end

  def already_registered?
    User.exists? email: @invitation.email
  end
end

app/models/invitation_generator.rb
# frozen_string_literal: true
require 'digest'

class InvitationGenerator
  def initialize(issuer:, email:)
    @issuer = issuer
    @email = email
  end

  def generate!
    invitation = Invitation.find_or_initialize_by token: token

    invitation.issuer = @issuer
    invitation.email = @email

    invitation.save

    [invitation, invitation.errors.full_messages]
  end

  private

  def token
    Digest::SHA256.hexdigest(
      [Rails.application.secrets[:secret_key_base], @email].join
    )
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound do
    render text: 'Not Found!', status: :not_found
  end
end

app/controllers/club_controller.rb
# frozen_string_literal: true
class ClubController < ApplicationController
  def catty; end
end

app/controllers/invitations_controller.rb
# frozen_string_literal: true
class InvitationsController < ApplicationController
  before_action :set_invitation, only: :resend

  def index
    @invitations = Invitation.where(issuer: current_user).order('created_at DESC')
  end

  def new; end

  def create
    invitation_generator = InvitationGenerator.new(issuer: current_user, email: invitation_params[:email])
    @invitation, errors = invitation_generator.generate!

    if errors.blank?
      invitation_delivery = InvitationDelivery.new @invitation
      _, errors = invitation_delivery.deliver!
    end

    render_flash errors

    redirect_to invitations_path
  end

  def resend
    invitation_delivery = InvitationDelivery.new @invitation
    _, errors = invitation_delivery.deliver!

    render_flash errors

    redirect_to invitations_path
  end

  private

  def render_flash(errors)
    if errors.blank?
      flash[:notice] = "Invitation sent to #{@invitation.email}"
    else
      flash[:alert] = errors.join('. ')
    end
  end

  def set_invitation
    @invitation = Invitation.where(issuer: current_user).find params[:id]
  end

  def invitation_params
    params.require(:invitation).permit(:email)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true
class RegistrationsController < ApplicationController
  skip_before_action :authenticate_user!
  before_action :set_invitation

  def new; end

  def create
    @user = User.new user_params
    @user.email = @invitation.email
    @user.confirmed_at = Time.zone.now

    if @user.save
      sign_in @user
      redirect_to root_path
    else
      flash[:alert] = @user.errors.full_messages.join('. ')
      render :new
    end
  end

  private

  def set_invitation
    @invitation = Invitation.find_by token: params[:token]
    raise ActiveRecord::RecordNotFound if @invitation.blank?
  end

  def user_params
    params.require(:registration).permit(:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
  def render_flash
    flash.each do |type, messages|
      Array.wrap(messages).each do |message|
        concat content_tag(:span, message, class: "label #{foundation_flash_class(type)}")
      end
    end
  end

  private

  def foundation_flash_class(type)
    case type.to_sym
    when :alert
      :alert
    when :notice
      :primary
    end
  end
end

app/helpers/club_helper.rb
# frozen_string_literal: true
module ClubHelper
end

app/helpers/invitations_helper.rb
# frozen_string_literal: true
module InvitationsHelper
end

app/helpers/registrations_helper.rb
# frozen_string_literal: true
module RegistrationsHelper
end

app/views/club/catty.html.erb
<div class="card">
  <%= image_tag asset_path('cat.png'), class: 'cute-catty-picture' %>
  <div class="card-section">
    <h4>Smelly Cat</h4>
    <p>Smelly Cat first appeared in the second season episode "The One With The Baby On The Bus" when Phoebe mentions the song in a conversation with Rachel.</p>
    <p><%= link_to 'Video', 'https://www.youtube.com/watch?v=92vTUFqy3gU' %></p>
  </div>
</div>

app/views/invitations/index.html.erb
<h1>Invitations</h1>

<table>
  <th>#</th>
  <th>Sent At</th>
  <th>Email</th>
  <th>Status</th>

  <tbody class='invitations'>
    <% @invitations.each do |invitation| %>
      <tr class='invitation'>
        <td><%= invitation.id %></td>
        <td><%= l invitation.sent_at if invitation.sent_at %></td>
        <td class='email'><%= invitation.email %></td>
        <td class='status'><%= invitation.state %></td>
        <td><%= link_to 'resend', resend_invitation_path(invitation), method: :post, class: "hollow button small #{:disabled if invitation.registered?}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/invitations/new.html.erb
<h1>Invite Your Friend</h1>

<%= form_tag invitations_path do %>
  <%= label_tag 'invitation[email]', 'Email' %>
  <%= email_field_tag 'invitation[email]', nil, placeholder: 'email', required: true %>

  <%= submit_tag 'Invite', class: 'button' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js" lang="en">
  <head>
    <title>Smelly Cat Club</title>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>

    <br />
    <center><% render_flash %></center>
    <br />

    <div class="row">
      <div class="medium-offset-2 medium-8 columns">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="top-bar">
  <div class="top-bar-title">
    <strong>
      <%= link_to root_path do %>
        Smelly Cat Club
      <% end %>
    </strong>
  </div>
  <% if user_signed_in? %>
    <div id="responsive-menu">
      <div class="top-bar-left">
        <ul class="menu">
          <li><%= link_to 'Invite Your Friend', new_invitation_path %></li>
          <li><%= link_to 'My Invitations', invitations_path %></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <li>Hello <%= current_user.email %>!</li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              Log out
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
</div>